### ISSUE TITLE
sidemenu title not working with ionic v1.0.0

### ISSUE THREAD

**Issue by moverly** [imsingh/ionic-animated-drawer#1]
Hi I m using it and it is fantastic. But I updated my ionic bundle from 1.0.0.rc to 1.0.0 for collection-repeat feature. The sidemenu title lost binding. 
http://stackoverflow.com/questions/30363540/ionicframework-version-update-change-my-sidemenu-lost-header

**Comment by imsingh** [comment]
@moverly Fixed!
